config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 名前は必須入力かつ20文字以内
    validates :name , length: { maximum: 20 } , presence: true
    
    # 年齢は必須入力かつ数字かつ3桁以内
    validates :age , numericality: { only_integer: true, greater_than: 0, less_than: 1000 },  presence: true

    # 内容は必須入力かつ2文字以上30文字以内
    validates :body , length: { minimum: 2, maximum: 30 } , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]  # edit, update, destroyの処理の前にmessageを設定する
  
  def index
    # Messageをすべて取得する
    @messages = Message.all
    @message = Message.new
  end
  
  def create
    #binding.pry
    @message = Message.new(message_params)
    if @message.save
      # メッセージの保存に成功した場合
      # リダイレクト
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージの保存に失敗した場合
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    #binding.pry
    if @message.update(message_params)
      # 更新に成功した場合
      # リダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 更新に失敗した場合
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path , notice: 'メッセージを削除しました'
  end
  
  private
  def message_params
    # パラメータを受け取る
    # params[:message]のパラメータで name ,age, bodyのみを許可する。
    # 返り値は ex:) {name: "入力されたname" , age: "入力されたage", body: "入力されたbody" }
    params.require(:message).permit(:name, :age, :body)
  end
  
  def set_message
    @message = Message.find(params[:id])

    if params.has_key?(:message)
      @return = params[:message][:return]
      
      #binding.pry
      if @return.to_i == 1
        # 戻る
        redirect_to root_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <% if controller.action_name == "edit" %>
  <script type="text/javascript">
    $(function(){
        $('#returnButton').text("Back");
    });
  </script>
  <% end %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-menu" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Message Board</a>
      </div>
      <div class="collapse navbar-collapse" id="nav-menu">
          <ul class="nav navbar-nav navbar-right">
              <li><a href=""><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Login</a></li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Language <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="#">Japanese</a></li>
                      <li><a href="#">English</a></li>
                  </ul>
              </li>
          </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_form.html.erb
<div class="row">
    <div class="col-sm-6">
        <fieldset>
            <div class="panel panel-default" style="background-color: #eeeeee;">
                <div class="panel-body" id="lang2"><legend class="f15em" id="title-post">Post</legend>
                    <div class="row">
                        <div class="col-xs-12">
                        <% if @message.errors.present? %>
                            <div class="alert alert-danger">
                                <%= alert %>
                                <ul>
                                    <% @message.errors.full_messages.each do |full_message| %>
                                    <li>
                                        <%= full_message %>
                                    </li>
                                    <% end %>
                                </ul>
                            </div>
                        <% end %>
                        <%= form_for(@message) do |f| %>
                            <div class="form-group mgt10">
                                <label id="input-name" for="name" class="control-label"><span class="glyphicon glyphicon-user" aria-hidden="true"> Name</label>
                                <p><%= f.text_field :name, class: "form-control", placeholder: "name", id: "name" %></p>
                            </div>
                            <div class="form-group mgt10">
                                <label id="input-name" for="age" class="control-label"><span class="glyphicon glyphicon-hourglass" aria-hidden="true"> Age</label>
                                <p><%= f.text_field :age, class: "number form-control", placeholder: "31", id: "age" %></p>
                            </div>
                            <div class="form-group mgt10">
                                <label id="input-message" for="message" class="control-label"><span class="glyphicon glyphicon-comment" aria-hidden="true"> Message</label>
                                <p><%= f.text_area :body, class: "form-control", placeholder: "Message", id: "message" %></p>
                            </div>
                            <%= f.submit "Post Message", class: "btn btn-sm btn-primary" %>
                            <% if controller.action_name == "edit" %>
                            <%= f.button "Back", class: "btn btn-sm btn-primary", type: "button", id: "returnButton", onclick: "history.back();" %>
                            <% end %>
                        <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>

app/views/messages/edit.html.erb
<h2>メッセージの編集</h2>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-primary">
    <div class="panel-heading" id="title-message">Message List</div>
    
    <div class="panel-body">
        <% @messages.each do |message| %>
            <span class="label label-info mgr5"><%= message.name %> <% if message.age %>(<%= message.age %>)<% end %></span>
            <%= message.body %>
            <%= link_to "edit" , edit_message_path(message), :class => "label label-success" %>
            <%= link_to "destroy" , message, method: :delete, data: { confirm: '削除してもよろしいですか？' }, :class => "label label-danger" %>
            <br />
        <% end %>
    </div>
</div>

<% #部分テンプレート読み込み %>
<%= render 'form' %>